# Site settings

title: La Taberna de Arkenan

#email: your-email@domain.com

description: > # this means to ignore newlines until "baseurl:"
  Bienvenido a la taberna de Arkenan.
  Pase usted.
  Tome un poco de programación.

#twitter_username: jekyllrb

github_username: Arkenan

excerpt_separator: <!---more--->
# Build settings

markdown: kramdown

theme: jekyll-theme-midnight

gems:
  - jekyll-feed
  - jekyll-paginate

exclude:
  - Gemfile
  - Gemfile.lock

baseurl: "" # the subpath of your site, e.g. /blog/

# Build settings
markdown: kramdown

paginate: 4

author: Tomás Arjovsky
